test:
  image: julia:1.10
  script:
    - |
      julia --project=@. --heap-size-hint=1.5G -e '
        include("install_deps.jl")
        using Pkg
        Pkg.build()
        Pkg.test(coverage=true)'
