name = "blockSQP"
uuid = "eedde146-038c-472b-a63b-c8c70ebda014"
authors = ["Christoph Plate <christoph.plate@ovgu.de>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
blockSQP_jll = "fec014c7-73d5-5f83-866b-eea102cb7f01"

[compat]
CxxWrap = "0.16.0"
