name = "blockSQP"
uuid = "eedde146-038c-472b-a63b-c8c70ebda014"
authors = ["Christoph Plate <christoph.plate@ovgu.de>", "Reinhold Wittmann <reinhold.wittmann@ovgu.de>"]
version = "0.1.0"

[deps]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[weakdeps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extensions]
ComponentArraysExtension = "ComponentArrays"
OptimizationExtension = ["Optimization", "Pkg"]

[compat]
ComponentArrays = "0.15"
ForwardDiff = "0.10"
Ipopt = "1.10"
Optimization = "~3.19.0, 4"
OptimizationMOI = "0.5"
SparseArrays = "1.10"
Symbolics = "6.38"
Test = "1"
julia = "1.6 - 1.11"

[extras]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationMOI = "fd9f6733-72f4-499f-8506-86b2bdd0dea1"
QPALM = "6c3e646c-629b-11e9-19d9-033f6272e8d4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Optimization", "ComponentArrays", "ForwardDiff", "Ipopt", "OptimizationMOI", "LinearAlgebra"]
